[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
node_layer1_weight = { path = "../initializers/node_layer1_weight"} 
node_layer1_bias = { path = "../initializers/node_layer1_bias"} 
node_layer2_weight = { path = "../initializers/node_layer2_weight"} 
node_layer2_bias = { path = "../initializers/node_layer2_bias"} 
node_output_layer_weight = { path = "../initializers/node_output_layer_weight"} 
node_output_layer_bias = { path = "../initializers/node_output_layer_bias"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "7d84a42" } 
[lib]
sierra-text = true